sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t smart-api-search .

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-1a-api"
  env: "Docker-1a-api-env"
  bucket_name: "elasticbeanstalk-us-east-1-886715373652"
  bucket_path: "docker-1a-api"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY